### PR TITLE
Fixed a typo in the Panel Description

### PR DESCRIPTION
**Pull request by JulieKuehl**

### CODE REVIEW

**Comment by ahmadawais** [comment]
Thanks for this, @JulieKuehl  Can squash your commits to one single commit?

**Comment by JulieKuehl** [comment]
Not sure I know how to do that. :-/

**Comment by ahmadawais** [comment]
It's a good time to learn https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ then :)

**Comment by ahmadawais** [comment]
@JulieKuehl Merged. I'll take care of it. Thanks.

**Comment by JulieKuehl** [comment]
Sorry, I was on holiday and you beat me to the merge. Thanks for the tutorial though!

**Pull request merged**
